add support for v2 basemap styles
Esri/esri-leaflet-vector pull request #175
Opened 2023-05-15 15:19 UTC by gowin20

Adds support for the [basemap styles service v2 beta](https://developers.arcgis.com/rest/basemap-styles/) as mentioned in #174 

* New `getBasemapStyleV2Url` function that returns a reference to the new v2 endpoint
* New `version` parameter in `VectorBasemapLayer` that specifies the endpoint to access (1 or 2, 1 by default)
* New `language` parameter that works with v2 of the service, accepts valid [language parameters](https://developers.arcgis.com/rest/basemap-styles/arcgis-outdoor-style-get/#language)

2023-05-15 23:00 UTC, gavinr requested changes
Overall looks solid. Here are some ideas, and also can you add some unit tests to `VectorBasemapLayerSpec.js` to test this new functionality? Thanks!

2023-05-16 21:46 UTC, gowin20 commented on examples/languages.html
> +        "Vietnamese": getLayer("vi")
It is currently static. I asked the team if they had any plans to add an endpoint to request a list of supported languages. Not sure if that will be added, we'll have to wait and see.

2023-05-17 03:32 UTC, gavinr approved these changes
Looks good! Thanks for adding the tests. Waiting for @patrickarlt to review before merge.

2023-05-27 00:01 UTC, gowin20 commented
included in #182

2023-05-27 00:01 UTC, closed without merging