updated maplibre-gl dependency to v3.3.1, passing all tests
Esri/esri-leaflet-vector pull request #201
Opened 2023-10-06 15:16 UTC by sdthaker

I've updated the dependency to v3.3.1, which happens to be the latest and also ran the tests. The results are attached below. Please let me know if I'm missing anything else since this is my very first time contributing to an open-source repo! :)

Test results after upgrading the maplibre-gl dependency to v3.3.1: 
![image](https://github.com/Esri/esri-leaflet-vector/assets/71615163/acfa43c1-6ed8-4b61-80e4-21631d622af5)

2023-10-06 19:15 UTC, patrickarlt requested changes
@gavinr this looks good be since there are no direct breaking changes for us I wonder if we should make this peer dependency something like `^2.0.0 || ^3.0.0` so show that we can support v2 OR v3 of MapLibre right now.

2023-10-09 20:40 UTC, gavinr-maps commented
@patrickarlt sounds good. I made that change. So this would not be a breaking change for esri-leaflet-vector then, correct? So we can release this under v4.1.1 ?

2023-10-09 20:44 UTC, gavinr-maps approved these changes

2023-10-18 17:56 UTC, merged

2023-10-18 19:53 UTC, gavinr-maps commented
This was released in [v4.2.1](https://github.com/Esri/esri-leaflet-vector/releases/tag/v4.2.1).